# InvisibilityTagFix - Configuration #
# Made by Giovanni75 aka Matocolotoe #

# Permission required to run /itf
permission: "itf.admin"

# Message which is displayed to players who don't have the above permission
permission-message: "§cYou do not have the required permission to run this command."

# Period (in ticks, minimum 1) of the task updating tags
refresh-frequency: 1
